export default {
    noField: true,
    props: {
        type: 'default',
        size: 'normal',
        iconPrefix: 'van-icon',
        iconPosition: 'left',
        tag: 'button',
        nativeType: 'button',
        block: false,
        plain: false,
        square: false,
        round: false,
        disabled: false,
        hairline: false,
        loading: false,
        loadingType: 'circular',
        loadingSize: '20px',
        replace: false,
    },
    style: {},
};