export default {
  noField: true,
  props: {
    active: 0,
    type: 'line',
    color: '#1989fa',
    background: 'white',
    duration: 0.3,
    lineWidth: '40px',
    lineHeight: '3px',
    animated: false,
    border: false,
    ellipsis: true,
    sticky: false,
    shrink: false,
    swipeable: false,
    lazyRender: true,
    scrollspy: false,
    showHeader: true,
    offsetTop: 0,
    swipeThreshold: 5,
  },
  items: [],
  style: {
    position: 'relative',
    width: '100%',
    height: '100%',
  },
};