export default {
    items: [],
    props: {
      overlay: true,
      position: 'center',
      duration: 0.3,
      'z-index': 2000,
      round: false,
      'destroy-on-close': false,
      'lock-scroll': true,
      'lazy-render': true,
      'close-on-popstate': false,
      'close-on-click-overlay': true,
      closeable: false,
      'close-icon-position': 'top-right',
      'transition-appear': false,
      'safe-area-inset-top': false,
      'safe-area-inset-bottom': false,
    },
    style: {
      position: 'fixed',
      width: '100%',
      height: '100%',
      top: 0,
      left: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      zIndex: 100,
    },
};